// <auto-generated />
using System;
using GuitarStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuitarStore.Migrations
{
    [DbContext(typeof(GuitarContext))]
    [Migration("20260408162502_UpdateImages")]
    partial class UpdateImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("GuitarStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Type = "Electric"
                        },
                        new
                        {
                            CategoryID = 2,
                            Type = "Acoustic"
                        },
                        new
                        {
                            CategoryID = 3,
                            Type = "Classical"
                        });
                });

            modelBuilder.Entity("GuitarStore.Models.Guitar", b =>
                {
                    b.Property<int>("GuitarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("GuitarID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Guitar", (string)null);

                    b.HasData(
                        new
                        {
                            GuitarID = 1,
                            Brand = "Fender",
                            CategoryID = 1,
                            Description = "Stratocaster - Iconic American electric with three single-coil pickups and contoured body.",
                            ImageUrl = "https://dummyimage.com/400x300/1a1a2e/ffffff&text=Fender+-+Stratocaster",
                            Price = 899.99m
                        },
                        new
                        {
                            GuitarID = 2,
                            Brand = "Gibson",
                            CategoryID = 1,
                            Description = "Les Paul Standard - Classic rock guitar with mahogany body and twin humbucker pickups.",
                            ImageUrl = "https://dummyimage.com/400x300/16213e/ffffff&text=Gibson+-+Les+Paul",
                            Price = 1299.99m
                        },
                        new
                        {
                            GuitarID = 3,
                            Brand = "Fender",
                            CategoryID = 1,
                            Description = "Telecaster - Twangy classic with two single-coil pickups and solid ash body.",
                            ImageUrl = "https://dummyimage.com/400x300/1b4332/ffffff&text=Fender+-+Telecaster",
                            Price = 849.99m
                        },
                        new
                        {
                            GuitarID = 4,
                            Brand = "Gibson",
                            CategoryID = 1,
                            Description = "SG Standard - Lightweight double cutaway with twin humbuckers and slim taper neck.",
                            ImageUrl = "https://dummyimage.com/400x300/6b2737/ffffff&text=Gibson+-+SG+Standard",
                            Price = 1099.99m
                        },
                        new
                        {
                            GuitarID = 5,
                            Brand = "Ibanez",
                            CategoryID = 1,
                            Description = "RG550 - High performance electric with Wizard neck and Edge tremolo system.",
                            ImageUrl = "https://dummyimage.com/400x300/d62828/ffffff&text=Ibanez+-+RG550",
                            Price = 699.99m
                        },
                        new
                        {
                            GuitarID = 6,
                            Brand = "PRS",
                            CategoryID = 1,
                            Description = "Custom 24 - Versatile electric with stunning figured maple top and wide-thin neck.",
                            ImageUrl = "https://dummyimage.com/400x300/4a0e8f/ffffff&text=PRS+-+Custom+24",
                            Price = 2199.99m
                        },
                        new
                        {
                            GuitarID = 7,
                            Brand = "ESP",
                            CategoryID = 1,
                            Description = "LTD EC-1000 - Professional electric with set-thru neck and EMG pickups.",
                            ImageUrl = "https://dummyimage.com/400x300/212529/ffffff&text=ESP+-+LTD+EC-1000",
                            Price = 799.99m
                        },
                        new
                        {
                            GuitarID = 8,
                            Brand = "Gretsch",
                            CategoryID = 1,
                            Description = "G2622 Streamliner - Semi-hollow body with dual broad'tron pickups.",
                            ImageUrl = "https://dummyimage.com/400x300/9c6644/ffffff&text=Gretsch+-+G2622",
                            Price = 449.99m
                        },
                        new
                        {
                            GuitarID = 9,
                            Brand = "Epiphone",
                            CategoryID = 1,
                            Description = "Casino - Fully hollow thinline with P-90 style dogear pickups.",
                            ImageUrl = "https://dummyimage.com/400x300/343a40/ffffff&text=Epiphone+-+Casino",
                            Price = 599.99m
                        },
                        new
                        {
                            GuitarID = 10,
                            Brand = "Schecter",
                            CategoryID = 1,
                            Description = "Hellraiser C-1 - High output electric with active EMG pickups and set neck.",
                            ImageUrl = "https://dummyimage.com/400x300/560bad/ffffff&text=Schecter+-+Hellraiser+C-1",
                            Price = 749.99m
                        },
                        new
                        {
                            GuitarID = 11,
                            Brand = "Martin",
                            CategoryID = 2,
                            Description = "D-28 - Premium dreadnought acoustic with Sitka spruce top and rosewood back.",
                            ImageUrl = "https://dummyimage.com/400x300/5c4033/ffffff&text=Martin+-+D-28",
                            Price = 1799.99m
                        },
                        new
                        {
                            GuitarID = 12,
                            Brand = "Taylor",
                            CategoryID = 2,
                            Description = "214ce - Grand Auditorium acoustic-electric with a warm balanced tone.",
                            ImageUrl = "https://dummyimage.com/400x300/533483/ffffff&text=Taylor+-+214ce",
                            Price = 999.99m
                        },
                        new
                        {
                            GuitarID = 13,
                            Brand = "Gibson",
                            CategoryID = 2,
                            Description = "J-45 Standard - Slope-shouldered dreadnought with warm vintage tone.",
                            ImageUrl = "https://dummyimage.com/400x300/3d1f00/ffffff&text=Gibson+-+J-45",
                            Price = 1599.99m
                        },
                        new
                        {
                            GuitarID = 14,
                            Brand = "Yamaha",
                            CategoryID = 2,
                            Description = "FG800 - Solid Sitka spruce top dreadnought with scalloped bracing.",
                            ImageUrl = "https://dummyimage.com/400x300/2b2d42/ffffff&text=Yamaha+-+FG800",
                            Price = 249.99m
                        },
                        new
                        {
                            GuitarID = 15,
                            Brand = "Seagull",
                            CategoryID = 2,
                            Description = "S6 Original - Canadian-made acoustic with cedar top and cherry back.",
                            ImageUrl = "https://dummyimage.com/400x300/4a7c59/ffffff&text=Seagull+-+S6+Original",
                            Price = 399.99m
                        },
                        new
                        {
                            GuitarID = 16,
                            Brand = "Takamine",
                            CategoryID = 2,
                            Description = "GN93CE - NEX body acoustic-electric with solid cedar top and rosewood.",
                            ImageUrl = "https://dummyimage.com/400x300/774936/ffffff&text=Takamine+-+GN93CE",
                            Price = 549.99m
                        },
                        new
                        {
                            GuitarID = 17,
                            Brand = "Yamaha",
                            CategoryID = 3,
                            Description = "CG182S - Classical with solid Engelmann spruce top and warm projecting sound.",
                            ImageUrl = "https://dummyimage.com/400x300/2b2d42/ffffff&text=Yamaha+-+CG182S",
                            Price = 449.99m
                        },
                        new
                        {
                            GuitarID = 18,
                            Brand = "Cordoba",
                            CategoryID = 3,
                            Description = "C9 Parlour - Solid cedar top classical with mahogany back and sides.",
                            ImageUrl = "https://dummyimage.com/400x300/5e3023/ffffff&text=Cordoba+-+C9+Parlour",
                            Price = 599.99m
                        },
                        new
                        {
                            GuitarID = 19,
                            Brand = "Kremona",
                            CategoryID = 3,
                            Description = "Soloist S65C - Bulgarian handcrafted classical with solid cedar top.",
                            ImageUrl = "https://dummyimage.com/400x300/1b4332/ffffff&text=Kremona+-+Soloist+S65C",
                            Price = 349.99m
                        },
                        new
                        {
                            GuitarID = 20,
                            Brand = "Alhambra",
                            CategoryID = 3,
                            Description = "3C - Spanish classical with solid Canadian cedar top and sapele back.",
                            ImageUrl = "https://dummyimage.com/400x300/6d4c41/ffffff&text=Alhambra+-+3C",
                            Price = 499.99m
                        });
                });

            modelBuilder.Entity("GuitarStore.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GuitarStore.Models.OrderedItem", b =>
                {
                    b.Property<int>("OrderedItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuitarID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderedItemID");

                    b.HasIndex("GuitarID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderedItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GuitarStore.Models.Guitar", b =>
                {
                    b.HasOne("GuitarStore.Models.Category", "Category")
                        .WithMany("Guitars")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GuitarStore.Models.OrderedItem", b =>
                {
                    b.HasOne("GuitarStore.Models.Guitar", "Guitar")
                        .WithMany()
                        .HasForeignKey("GuitarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuitarStore.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guitar");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuitarStore.Models.Category", b =>
                {
                    b.Navigation("Guitars");
                });

            modelBuilder.Entity("GuitarStore.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
